/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MedicineInfo;

import java.awt.Desktop;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 * 
 */

public class fontpage extends javax.swing.JFrame {
             private ArrayList<MedicineInfo> Item = new ArrayList<>();
             int count = 0 ;
    public fontpage() {
        initComponents();
        showDate();
        showTime();
    }
        private void showDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy/MM/dd");
        lblDate.setText("Date: " + s.format(d)); //Displays current date in lblDate
    }

    private void showTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("H:mm:ss a");
                lblTime.setText("Time: " + s.format(d)); ////Displays current time in lblTime
            }
        }).start();
    }
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCatogries = new javax.swing.ButtonGroup();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jDialog1 = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lblCode = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        lblRanking = new javax.swing.JLabel();
        lblFee = new javax.swing.JLabel();
        lblDiscount = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtManufacture = new javax.swing.JTextField();
        cmbType = new javax.swing.JComboBox<>();
        rbtnLocal = new javax.swing.JRadioButton();
        rbtImport = new javax.swing.JRadioButton();
        txtprice = new javax.swing.JTextField();
        cmbDiscount = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        txtSerialno = new javax.swing.JTextField();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnsearchbymedicineType = new javax.swing.JButton();
        cmbMedicineType = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        btnSearchbyManufature = new javax.swing.JButton();
        txtSearchbyfee = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableInfo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmuOpen = new javax.swing.JMenuItem();
        JmuSave = new javax.swing.JMenuItem();
        jmuImport = new javax.swing.JMenuItem();
        jumExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jLabel12.setText("jLabel12");

        jTextField1.setText("jTextField1");

        jDialog1.setPreferredSize(new java.awt.Dimension(600, 700));
        jDialog1.setSize(new java.awt.Dimension(700, 500));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setText("of medicine, stock in the table such as serial number, name, ");

        jLabel11.setText("medicine types, manufacture, category, price, and discount. ");

        jLabel13.setText(" to various medicine items by selecting the specific medicine types or prices");

        jLabel14.setText("This application makes the user easily search and navigate to various medicine items by selecting the specific medicine types or prices");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Pharmastash");

        jLabel9.setText("This application system is developed for managing data ");

        jLabel8.setText("Pharmastash is software that's sales medicine of all types.");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jButton1))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel11))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(289, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblCode.setText("Serial No");

        lblName.setText("Medicine Name ");

        lblAddress.setText("Manufacturer");

        lblType.setText("Medicine Type");

        lblRanking.setText("Catogries ");

        lblFee.setText("Price ");

        lblDiscount.setText("Discount");

        txtManufacture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManufactureActionPerformed(evt);
            }
        });

        cmbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Liquid", "Tablet", "Capsules", "Topical Medicine", "Drops", "InHalers", "Injections" }));
        cmbType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTypeActionPerformed(evt);
            }
        });

        btnCatogries.add(rbtnLocal);
        rbtnLocal.setSelected(true);
        rbtnLocal.setText("Local");

        btnCatogries.add(rbtImport);
        rbtImport.setText("Importated");

        cmbDiscount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10%", "20%", "30%", "40%", "50%", "60%", "70%", "80%", "90%", "100%" }));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblRanking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDiscount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtName)
                            .addComponent(txtManufacture)
                            .addComponent(cmbType, 0, 161, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rbtnLocal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtImport))
                            .addComponent(cmbDiscount, 0, 161, Short.MAX_VALUE)
                            .addComponent(txtprice)
                            .addComponent(txtSerialno)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnAdd)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExit)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCode, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSerialno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtManufacture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblType, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnLocal)
                    .addComponent(rbtImport))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFee, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnClear)
                    .addComponent(btnExit))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Medicine", jPanel2);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Search By MedicineType", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Medicine Type");

        btnsearchbymedicineType.setText("Applied");
        btnsearchbymedicineType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchbymedicineTypeActionPerformed(evt);
            }
        });

        cmbMedicineType.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cmbMedicineType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Liquid", "Tablet", "Capsules", "Topical Medicine", "Drops", "InHalers", "Injections" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnsearchbymedicineType, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMedicineType, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbMedicineType, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnsearchbymedicineType)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Search by Price ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        btnSearchbyManufature.setText("Applied");
        btnSearchbyManufature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchbyManufatureActionPerformed(evt);
            }
        });

        txtSearchbyfee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchbyfeeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Price");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(txtSearchbyfee, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(btnSearchbyManufature)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchbyfee, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnSearchbyManufature)
                .addContainerGap())
        );

        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("", jPanel3);

        jTabbedPane1.addTab("Search Medicine", jTabbedPane2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 390, 480));
        jTabbedPane1.getAccessibleContext().setAccessibleName("Add Medicine ");

        jPanel1.setToolTipText("Data");

        tableInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Serial Number ", "Medicine Name ", "Manufacture", "Medicine Types", "Categories", "Price ", "Discount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableInfo);
        if (tableInfo.getColumnModel().getColumnCount() > 0) {
            tableInfo.getColumnModel().getColumn(0).setResizable(false);
            tableInfo.getColumnModel().getColumn(1).setResizable(false);
            tableInfo.getColumnModel().getColumn(2).setResizable(false);
            tableInfo.getColumnModel().getColumn(3).setResizable(false);
            tableInfo.getColumnModel().getColumn(4).setResizable(false);
            tableInfo.getColumnModel().getColumn(5).setResizable(false);
            tableInfo.getColumnModel().getColumn(6).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Medicine Information ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 948, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 960, 490));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 51));
        jLabel6.setText("Pharmastash");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 330, 50));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 400, 450));

        lblTime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 50, 140, 20));

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 10, 140, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MedicineInfo/background.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 650));

        jMenuBar1.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N

        jMenu1.setText("File");

        jmuOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jmuOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MedicineInfo/icons8_folder_30px.png"))); // NOI18N
        jmuOpen.setText("Open");
        jmuOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmuOpenActionPerformed(evt);
            }
        });
        jMenu1.add(jmuOpen);

        JmuSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        JmuSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MedicineInfo/icons8_save_30px.png"))); // NOI18N
        JmuSave.setText("Save");
        JmuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmuSaveActionPerformed(evt);
            }
        });
        jMenu1.add(JmuSave);

        jmuImport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jmuImport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MedicineInfo/icons8_import_30px.png"))); // NOI18N
        jmuImport.setText("Import");
        jmuImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmuImportActionPerformed(evt);
            }
        });
        jMenu1.add(jmuImport);

        jumExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jumExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MedicineInfo/icons8_exit_24px.png"))); // NOI18N
        jumExit.setText("Exit");
        jumExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumExitActionPerformed(evt);
            }
        });
        jMenu1.add(jumExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MedicineInfo/icons8_faq_26px.png"))); // NOI18N
        jMenuItem1.setText("Help");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("About");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MedicineInfo/icons8_about_24px.png"))); // NOI18N
        jMenuItem2.setText("About ");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmuImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmuImportActionPerformed
       try {
            File selectedFile;
            selectedFile = new File("C:\\Users\\User\\Documents\\NetBeansProjects\\MedicineInfo\\src\\MedicineInfo\\Data\\data.csv");
            if(selectedFile.exists()) {
                if(selectedFile.length()==0) {
                    JOptionPane.showMessageDialog(rootPane,"There is No Previously Saved Data" ,"Error!!",JOptionPane.ERROR_MESSAGE); 
                }
                else{
                    BufferedReader br = new BufferedReader(new FileReader(selectedFile));
                    Object[] lines = br.lines().toArray();
                    int rowCount = tableInfo.getRowCount();
                    int nextRow = 0;
                    boolean emptyRowFlag = false;
                    String p;

                    for (int i = 0; i < lines.length; i++) {  
                        String[] row = lines[i].toString().split(",");
                        do {
                            p = (String) tableInfo.getValueAt(nextRow, 0);
                    
                            if (p != null && p.length() != 0) {
                                nextRow++;
                            } 
                    
                            else {
                                emptyRowFlag = true;
                            }
                        }
                        while (nextRow < rowCount && !emptyRowFlag);

                        if (emptyRowFlag) {
                            int colCount = tableInfo.getColumnCount();
                    
                            if (nextRow < rowCount) {

                                for (int j = 0; j < colCount; j++) {
                                    tableInfo.setValueAt(row[j], nextRow, j);
                                }
                            }
                        } 
                        else {
                            JOptionPane.showMessageDialog(rootPane, "No Empty Row Found!!", "Error!!", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                }
            } 
            else{
                selectedFile.createNewFile();
                JOptionPane.showMessageDialog(rootPane,"There is No Previously Saved Data" ,"Error!!",JOptionPane.ERROR_MESSAGE); 
                return;
            }
        }
        
        catch (Exception ex) {
            Logger.getLogger(MedicineInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
 

       


    }//GEN-LAST:event_jmuImportActionPerformed
   private void save() {
            File file = new File("C:\\Users\\User\\Documents\\NetBeansProjects\\MedicineInfo\\src\\MedicineInfo\\Data\\data.csv");//Loading of file
        
        try (FileWriter wr = new FileWriter(file)) { 
                for (MedicineInfo s : Item) {
                String val[] = {s.getSerialNumber(), s.getname(), s.getManufacture(), s.getmedicinetype(),s.getcatagory(), Integer.toString(s.getprice()), s.getDiscount()};
            
            if (file.isFile()) {
                file.createNewFile();
            }    
                for (int i = 0; i <= val.length; i++) {
                    wr.append(val[i]);
                    if (i == val.length - 1) {
                        break;
                    }
                    wr.append(",");//
                }
                wr.append("\n");
            }  
            wr.flush();
            wr.close();
        }
        catch (IOException ex) {
            Logger.getLogger(MedicineInfo.class.getName()).log(Level.SEVERE, null, ex);
    }
   }
   
  public void readCSV() {
  try {
        BufferedReader bffr = new BufferedReader(new FileReader("Demo.csv"));
        } catch (FileNotFoundException ex) {
              JOptionPane.showMessageDialog(this, "File not Found");
        }catch(IOException ex){
           JOptionPane.showMessageDialog(this, "IOException occured.");
        }
  }
    private void JmuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmuSaveActionPerformed
        // TODO add your handling code here:
          if(Item.size()>=1) {
            save();
            JOptionPane.showMessageDialog(this, "Data is sucessfully Saved ", "Sucessfull!!", JOptionPane.INFORMATION_MESSAGE);    
        }
        else {
            JOptionPane.showMessageDialog(rootPane, "No Any Data Inserted in Table!!", "Error!!", JOptionPane.ERROR_MESSAGE);      
        }
    }//GEN-LAST:event_JmuSaveActionPerformed

    private void jmuOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmuOpenActionPerformed
        // TODO add your handling code here:
          try {
            File file = new File("C:\\Users\\User\\Documents\\NetBeansProjects\\MedicineInfo\\src\\MedicineInfo\\Data\\data.csv"); //sets file location
            
            if(file.exists()) {
                if(Desktop.isDesktopSupported()) {
                    Desktop.getDesktop().open(file); //Opens the previously saved file
                }
                else {
                    JOptionPane.showMessageDialog(rootPane,"Not Supported in Desktop" ,"Error!!",JOptionPane.ERROR_MESSAGE); 
                }
            }
            else {
                JOptionPane.showMessageDialog(rootPane,"File Doesn't Exists." ,"Error!!",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (HeadlessException | IOException ex) {
            Logger.getLogger(MedicineInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jmuOpenActionPerformed

    
    private void jumExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumExitActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(rootPane,"Do You Want To Close?","Warning!!",JOptionPane.YES_NO_OPTION); //Asks user to exit the program
        if(result == 0) {
            System.exit(0);
        }
        else {
            return;
        }
    }//GEN-LAST:event_jumExitActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
            int result = JOptionPane.showConfirmDialog(rootPane,"Do You Want To Close?","Warning!!",JOptionPane.YES_NO_OPTION); //Asks user to exit the program
        if(result == 0) {
            System.exit(0);
        }
        else {
            return;
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtSearchbyfeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchbyfeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchbyfeeActionPerformed

    private void btnSearchbyManufatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchbyManufatureActionPerformed
        // TODO add your handling code here:
        try {

            mergeSort(Item); //calls mergeSort() andd pass the array list as parameter
            int price = Integer.parseInt(txtSearchbyfee.getText().trim()); //converts string to integer type
            int i = binarySearch(Item,0,Item.size()-1,price);

            if (i == -1) {
                JOptionPane.showMessageDialog(rootPane,"There is No Data with that Price." ,"No Any Data!!",JOptionPane.INFORMATION_MESSAGE);
            }

            else { //displaying searched details
                JOptionPane.showMessageDialog(rootPane,"\n"+" SerialNumber: "+Item.get(i).getSerialNumber()+"\n medicine Name: "+Item.get(i).getname()+"\n price: "+Item.get(i).getprice(),"Medicine Information",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch(NumberFormatException nfe) { //exception handling
            if (txtSearchbyfee.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane,"No Any Value is Inserted." ,"Empty Text Fields!!",JOptionPane.ERROR_MESSAGE);
            }            else {
                JOptionPane.showMessageDialog(rootPane,"Please Enter Correct Data Type" ,"Error Data Type!!",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSearchbyManufatureActionPerformed

    private void btnsearchbymedicineTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchbymedicineTypeActionPerformed
        // TODO add your handling code here:
        String medicinetype = "";
        String cKey = (String)cmbMedicineType.getSelectedItem(); //selecting key value from comboBox

        for(MedicineInfo c:Item) {
            if(c.getmedicinetype().equals(cKey)) {
                medicinetype +=  " Model Number:"+c.getSerialNumber()+"\n Name:"+c.getname()+"\n Price:"+c.getprice()+"\n Catagory:"+c.getManufacture()+"\n\n"; //printing searched values
            }
        }

        if(!medicinetype.equals("")) {
            JOptionPane.showMessageDialog(rootPane," The Item is:"+"\n" + medicinetype);
        }
        else {
            JOptionPane.showMessageDialog(rootPane,"No Values in this Category" ,"No Such Data",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnsearchbymedicineTypeActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
            int result = JOptionPane.showConfirmDialog(rootPane,"Do You Want To Close?","Warning!!",JOptionPane.YES_NO_OPTION); //Asks user to exit the program
        if(result == 0) {
            System.exit(0);
        }
        else {
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
try{
        String  serialnumber = txtSerialno.getText().trim();
        String name = txtName.getText().trim();
        String manufacture = txtManufacture.getText().trim();
        String medicinetype = (String)cmbType.getSelectedItem();
        String catagoryTypes;
        if (rbtnLocal.isSelected() == true){
            catagoryTypes = "Local";
        }
        else{
            catagoryTypes = "Imporated";
        }
        String catagory = catagoryTypes;
        int price =Integer.parseInt(txtprice.getText().trim());
        String discount = (String)cmbDiscount.getSelectedItem();
        DefaultTableModel dmf = (DefaultTableModel)tableInfo.getModel();

        for (MedicineInfo n :Item){
            if (serialnumber.equals(n.getSerialNumber())){
                JOptionPane.showMessageDialog(this,"SerialNumber Same","Error",JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        if (!serialnumber.isEmpty()&&!name.isEmpty()&&!manufacture.isEmpty()&&!medicinetype.isEmpty()&&!catagory.isEmpty()&&!discount.isEmpty()&& price > 0  ){
            String []Values = {serialnumber,name,manufacture,medicinetype,catagory,Integer.toString(price),discount};
            dmf.addRow(Values);
            MedicineInfo td = new MedicineInfo(serialnumber,name,medicinetype,catagory,price,discount,manufacture);
            Item.add(td);
        } 

        else{
            JOptionPane.showMessageDialog(this, "The number is invalid");

        }
}
catch(NumberFormatException nfe ){
    JOptionPane.showMessageDialog(rootPane, "Invalid Input or Missing TextField", "Error!!", JOptionPane.ERROR_MESSAGE);
}
 catch (NullPointerException npe) {
            JOptionPane.showMessageDialog(rootPane, "No Data, Check Your Input", "Error!!", JOptionPane.ERROR_MESSAGE);
 }
    }//GEN-LAST:event_btnAddActionPerformed

    private void cmbTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTypeActionPerformed

    private void txtManufactureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManufactureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManufactureActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(rootPane,"Do You Want To Clear All The Text Fields?","Warning!!",JOptionPane.YES_NO_OPTION);
        if (result == 0){
            txtSerialno.setText("");
            txtName.setText("");
            txtManufacture.setText("");
            txtprice.setText("");
        }
        else {
            return;
        }
        
    
    }//GEN-LAST:event_btnClearActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
            try {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "C:\\Users\\User\\Documents\\NetBeansProjects\\MedicineInfo\\src\\MedicineInfo\\manual.pdf");
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Sorry, There is no FAQs", " Error.", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
            jDialog1.show();
        jDialog1.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        return;
    }//GEN-LAST:event_jButton1ActionPerformed
   public void mergeSort(ArrayList<MedicineInfo> price){
         if (price.size()<= 1){
             return ;
         }
    int FstLength = price.size()/2;
    int secLength = price.size()- FstLength;
    ArrayList<MedicineInfo> first = new ArrayList();
    ArrayList<MedicineInfo> secound = new ArrayList();
    for (int i = 0; i <FstLength;i++){
        first.add(price.get(i));
    }
    for (int i = 0 ; i< secLength; i++){
        secound.add(price.get(FstLength + i));
        
    }
    mergeSort(first);
    mergeSort(secound);
    merge(first,secound, price);
}
   public static int binarySearch(ArrayList<MedicineInfo> priceSearch, int low, int high, int key) {  
        int mid = (low + high)/2;  
        if (low <= high){ 
            
            if ( priceSearch.get(mid).getprice() == key ){  
                return mid;     
            }
            
            else if ( priceSearch.get(mid).getprice() > key ){  
                return binarySearch(priceSearch, low, mid-1, key);
            }
            
            else{  
                return binarySearch(priceSearch, mid+1, high, key); 
            }  
        }  
        
        else { 
            return -1;
        }  
    }  
   public static void merge(ArrayList<MedicineInfo>first,ArrayList<MedicineInfo>second, ArrayList<MedicineInfo>price){
              int iFirst = 0;
        int iSecond = 0;
        int j = 0;
        
        while (iFirst < first.size() && iSecond < second.size()) {
            if (first.get(iFirst).getprice() < second.get(iSecond).getprice()) {
                price.set(j, first.get(iFirst));
                iFirst++;
            }
            else {
                price.set(j, second.get(iSecond));
                iSecond++;
            }
            j++;
        }
        
        while (iFirst < first.size()) {
            price.set(j, first.get(iFirst));
            iFirst++;
            j++;
        }

        while (iSecond < second.size()) {
            price.set(j, second.get(iSecond));
            iSecond++;
            j++;
        }
   }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fontpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fontpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fontpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fontpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new fontpage().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JmuSave;
    private javax.swing.JButton btnAdd;
    private javax.swing.ButtonGroup btnCatogries;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSearchbyManufature;
    private javax.swing.JButton btnsearchbymedicineType;
    private javax.swing.JComboBox<String> cmbDiscount;
    private javax.swing.JComboBox<String> cmbMedicineType;
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JMenuItem jmuImport;
    private javax.swing.JMenuItem jmuOpen;
    private javax.swing.JMenuItem jumExit;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCode;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDiscount;
    private javax.swing.JLabel lblFee;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRanking;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblType;
    private javax.swing.JRadioButton rbtImport;
    private javax.swing.JRadioButton rbtnLocal;
    private javax.swing.JTable tableInfo;
    private javax.swing.JTextField txtManufacture;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSearchbyfee;
    private javax.swing.JTextField txtSerialno;
    private javax.swing.JTextField txtprice;
    // End of variables declaration//GEN-END:variables


}
